### ISSUE TITLE
Create Cluster Simulation Framework

### ISSUE THREAD

**Issue by bbengfort** [tipsybear/actors-simulation#17]
So what we need is a cluster simulation framework that behaves similarly to a hybrid OpenMP + MPI device. This needs to happen in advance of #13 so that I can build what is essentially the actor scheduler on top of it. 

I think the primary things we need to implement in the simulation is something to set up some number of nodes that is configurable with a # of processors, memory, and bandwidth. We should simulate a linear model of performance, where the number of processors increase the speed. Memory perhaps we don't have to think about too much, but we should at least leave a stub for it. 

The primary thing we'll want to look at is the communication framework. We want to have some means of simulating passing messages over the network by specifying some bandwidth and latency. My thought is to use a resource with a certain capacity to simulate bandwidth. Latency can be topology driven; which means we also need a way to simulate the interconnects between nodes.

**Comment by looselycoupled** [comment]
Can you go into topology a little more?  Are you thinking bus topology vs mesh or something?

Trying to figure out the granularity of what we need.  For instance, we could simulate putting our cluster of nodes over 1+ subnets.  That way we could introduce WAN delay across segments or network segmentation.  After some thought this may be overkill but could still be useful.

I was surprised to read the idea for linear speedup for more CPUs.  Along this line I was thinking that perhaps a "job" object could have an amount of "work" that needs to be processed.  The duration would then be a function of the number of available CPUs vs the amount of work.  I've been trying to square this in my mind with the previous ideas about treating the CPUs as available resources on the node such that each job would use only one CPU.

I've been brainstorming some competing designs and would like to review tomorrow after class.  I think the programming for this should go quickly once I'm clear on a few points.

**Comment by bbengfort** [comment]
For topology I might have started thinking about hypercubes and all that - but it's probably not necessary for what we're doing right now. We might have to represent a network with switches - but for now, let's just do all to all connections between the nodes. I do like the idea of subnets - this would give us the idea of "racks" of local machines -- which is very normal in a cluster. 

Well, what you described is exactly a linear model for CPUs - but we do need to do allocation to make our simulation work. 

Let's definitely catch up soon; because we need to get this simulation under way ASAP.

**Comment by bbengfort** [comment]
Super happy about the whiteboard session today; I think we've made good progress. 

To close this issue, let's get the API stubs in and then we can open specific issues for other pieces.

**Comment by looselycoupled** [comment]
Agreed.  I had hoped to get this done in the afternoon but will probably have to wait until this evening.
