### ISSUE TITLE
The streaming data service quits early

### ISSUE THREAD

**Issue by bbengfort** [tipsybear/actors-simulation#22]
the streaming data service quits after 5 time steps when calling the service route handler but is fine when not calling the route handler. Not sure why.

**Comment by bbengfort** [comment]
See [gvas/actors/manager.py Line #121](https://github.com/tipsybear/actors-simulation/blob/develop/gvas/actors/manager.py#L121) - if you comment out the message send, then the streaming data service continues along fine.

**Comment by bbengfort** [comment]
@looselycoupled a bit more description for you to take a look at this. 

When you look at `balance.py`, the `StreamingData` process ([Line 42](https://github.com/tipsybear/actors-simulation/blob/develop/gvas/sims/balance.py#L42)) is supposed to generate a number of messages (according to the volume it gets from a normal distribution called stream) and send those to the Actor service (an instance of Actor manager). It saves it's last volume so that it can be monitored by the main simulation. 

However, for some reason, this quits when the cluster is full utilized, e.g. 100% of actors are activated. You can see this in the following figure: (the flatline is just the last recorded volume for the stream). 

![flatline](https://cloud.githubusercontent.com/assets/745966/11823802/220550f0-a344-11e5-8e80-61b53ce0a060.png)

However if you comment out the `node.send` (see above comment) call which sends the message (and is apparently causing the streaming data process to become idle) then the stream works as expected, except that no messages are being sent and received: 

![comment](https://cloud.githubusercontent.com/assets/745966/11823852/5d36a278-a344-11e5-80b5-9655b25f7f24.png)

Here, the number of messages in the queue just grows forever and is never dispatched. 

Could use your help figuring this out!

**Comment by looselycoupled** [comment]
Committed a fix last night.  Let me know if the issue continues.

**Comment by looselycoupled** [comment]
![balancesimulation-20151216](https://cloud.githubusercontent.com/assets/41358/11845275/2c4e83d6-a3e1-11e5-973e-00ced867721b.png)
