### ISSUE TITLE
Simulation runner

### ISSUE THREAD

**Issue by bbengfort** [tipsybear/actors-simulation#7]
Need something similar to Smoak drivers that can basically encapsulate a simulation from the command line and run it.

**Comment by bbengfort** [comment]
@looselycoupled -- we can come up with a spec here if you want; unless you feel comfortable moving forward?

**Comment by bbengfort** [comment]
Spec:
- [x] In the `sims.__init__.py` create a data structure to hold the name, description, and class of all the simulations we want exposed by the runner. 
- [x] The runner should have have two commands: run and list
- [x] The list command simply shows and optionally describes the available simulations
- [x] The run command takes as an argument the short name of a simulation, loads and runs it. 
- [x] The run command should take a configuration file as an argument, which will then use Confire to modify the settings for that run in particular. 
- [x] The run command will need to specify output for the simulations (default is stdout). 

Not sure if I'm missing anything here, but hopefully that's clear enough.

**Comment by looselycoupled** [comment]
Of course I saw this after I merged my branch.  Will create a new local to implement the missing spec features.

**Comment by looselycoupled** [comment]
This should be complete though the listing is a little ugly (we can pretty it up later).

Let me know if there is anything that needs reworked or that I may have missed.

**Comment by bbengfort** [comment]
@looselycoupled - looks good to me, thanks! Thoughts on next steps?
